### ISSUE TITLE
Allow decimal entries for fields: length, width, and depth

### ISSUE THREAD

**Issue by CarlSchoch** [mapiworks/BeachObserver#16]

**Comment by mapiworks** [comment]
Could this be solved via input in cm? Other wise we would need to extend all leaf nodes as follows: width: {mandatory: false, decimals: true}, count: {mandatory: true, decimals: false}, volume: null, etc

**Comment by mapiworks** [comment]
And potentially add units, eg {unit: "m"}, {unit: "pc"}, etc
