### ISSUE TITLE
New feature: when submitting observation there should be an option to for "private" so it gets entered in the database but does not show on the map. This would be useful for culturally sensitive objects and some oil spills. This should also be edit option even after posting.

### ISSUE THREAD

**Issue by cschochak** [mapiworks/BeachObserver#6]

**Comment by mapiworks** [comment]
Added a "public?" checkbox to report submit screen. The map shows public reports only plus reports owned by the user.

**Comment by cschochak** [comment]
Nice Mario. I need to think of a way for an organization to be able to link together their observations together on a map. For example if the staff at CORI wanted show all their cumulative observations, how could that happen with using a shared email account?

 

-Carl

**Comment by mapiworks** [comment]
This can be realized by introducing "organizations" on top of users as a one-to-many relationship. This could be administrated via the admin interface.

**Comment by cschochak** [comment]
Thanks Mario. Have a good night…
